[package]
name = "s3-file-connector"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
fuser = { path = "../vendor/fuser", features = ["abi-7-28"] }
s3-client = { path = "../s3-client" }
aws-crt-s3 = { path = "../aws-crt-s3" }

anyhow = { version = "1.0.64", features = ["backtrace"] }
async-trait = "0.1.57"
clap = { version = "3.2.12", features = ["derive"] }
ctrlc = "3.2.3"
libc = "0.2.126"
tracing = { version = "0.1.35", default-features = false, features = ["std", "log"] }
tracing-subscriber = { version = "0.3.14", features = ["fmt", "env-filter"] }

[dev-dependencies]
base16ct = { version = "0.1.1", features = ["alloc"] }
sha2 = "0.10.6"
tempfile = "3.3.0"
test-log = { version = "0.2.11", default-features = false, features = ["trace"] }

[features]
fuse_tests = []
