[package]
name = "aws-crt-s3"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
publish = false

[dependencies]
aws-crt-s3-sys = { path = "../aws-crt-s3-sys" }
libc = "0.2.132"
static_assertions = "1.1.0"
futures = "0.3.24"
crossbeam = "0.8.2"
