name: Rust Unit Tests

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  S3_BUCKET_NAME: s3-file-connector-github-test-bucket
  S3_BUCKET_TEST_PREFIX: github-actions-tmp/run-${{ github.run_id }}/attempt-${{ github.run_attempt }}

jobs:
  test:
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::360461222476:role/GitHub-Actions-Role
        aws-region: us-east-1
    # Lifecycle on the bucket cleans these objects up for us
    - name: Put test object
      run: |
        TMP=$(mktemp)
        echo "Test object to check bucket exists" > $TMP
        aws s3api put-object --bucket $S3_BUCKET_NAME --key $S3_BUCKET_TEST_PREFIX/test --body $TMP
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install fuse
      run: sudo apt-get install fuse libfuse2 libfuse-dev
    - name: Build
      run: cargo build --examples
    - name: Run tests
      run: cargo test
