name: CI

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  # RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  S3_BUCKET_NAME: s3-file-connector-github-test-bucket
  S3_BUCKET_TEST_PREFIX: github-actions-tmp/run-${{ github.run_id }}/attempt-${{ github.run_attempt }}/
  S3_BUCKET_BENCH_FILE: read-only-mount-test/bench1GB.bin
  S3_BUCKET_SMALL_BENCH_FILE: read-only-mount-test/bench5MB.bin
  # A bucket our IAM role has no access to, but is in the right region, for permissions tests
  S3_FORBIDDEN_BUCKET_NAME: s3-file-connector-github-test-bucket-forbidden
  S3_REGION: us-east-1
  RUST_FEATURES: fuse_tests,s3_tests

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        fuse: [fuse, fuse3]

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::360461222476:role/GitHub-Actions-Role
        aws-region: us-east-1
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install fuse
      run: sudo apt-get install ${{ matrix.fuse }} lib${{ matrix.fuse }}-dev
    - name: Configure fuse
      run: echo 'user_allow_other' | sudo tee -a /etc/fuse.conf
    - name: Run tests
      run: cargo test --features $RUST_FEATURES

  bench:
    name: Benchmark
    runs-on: self-hosted

    permissions:
      id-token: write
      contents: write

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::360461222476:role/GitHub-Actions-Role
        aws-region: us-east-1
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Update package list
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get -y install cmake libclang-dev libunwind-dev pkg-config
    - name: Install fuse
      run: sudo apt-get -y install fuse libfuse-dev
    - name: Configure fuse
      run: echo 'user_allow_other' | sudo tee -a /etc/fuse.conf
    - name: Install Rust
      run: cargo --version || curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Update PATH
      run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH
    - name: Run benchmark
      run: cargo bench -- fs --verbose | s3-file-connector/scripts/bench_parser.sh | tee output.txt
    - name: Store benchmark result
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'customBiggerIsBetter'
        output-file-path: output.txt
        alert-threshold: "200%"
        fail-on-alert: true
        # GitHub API token to make a commit comment
        github-token: ${{ secrets.GITHUB_TOKEN }}
        # Push and deploy GitHub pages branch automatically
        auto-push: true
        comment-on-alert: true

  check:
    name: Check all targets
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install fuse
      run: sudo apt-get install fuse libfuse-dev
    - name: Check all targets
      run: cargo check --all-targets --features $RUST_FEATURES

  shuttle:
    name: Shuttle tests
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install fuse
      run: sudo apt-get install fuse libfuse-dev
    - name: Run Shuttle tests
      run: cargo test -p s3-file-connector --features shuttle -- shuttle

  asan:
    name: Address sanitizer
    runs-on: ubuntu-22.04

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::360461222476:role/GitHub-Actions-Role
        aws-region: us-east-1
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install nightly Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
        components: rust-src
    - name: Install fuse
      run: sudo apt-get install fuse3 libfuse3-dev
    - name: Install llvm-dev
      run: sudo apt-get install llvm-dev
    - name: Configure fuse
      run: echo 'user_allow_other' | sudo tee -a /etc/fuse.conf
    - name: Validate ASan is working
      run: make test-asan-working
    - name: Run tests
      run: make test-asan

  rustfmt:
    name: Formatting
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install rustfmt
        run: rustup component add rustfmt
      - name: Check format
        run: make fmt-check

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install fuse
        run: sudo apt-get install fuse libfuse2 libfuse-dev
      - name: Run Clippy
        run: make clippy

  docs:
    name: CRT docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build CRT binding documentation
        run: cargo doc --no-deps -p aws-crt-s3

  deny:
    name: Licenses
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run cargo deny
        uses: EmbarkStudios/cargo-deny-action@v1
